plugins:
  - jemoji
sass:
  sass_dir: _sass

monNom : ktn

docs:
  Plugins:
    defauts:
      icon : defauts_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    EaseeCharger:
      icon: EaseeCharger_icon.png
      pages:
        doc: index.html
    EVcharger:
      icon : EVcharger_icon.png
      pages:
        doc utilisateurs: index.html
        changeLog: changelog.html
        Ajout d'un modèle: ajoutModel.html
        Cmd des chargeurs: cmdCharger.html
    swassist:
      icon : swassist_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
  Utilitaires:
    traduitjdm: 
      pages:
        doc: index.html
        changeLog: release_notes.html
