sass:
  sass_dir: _sass

monNom : ktn

docs:
  Plugins:
    chargeurVE:
      icon : chargeurVE_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    swassist:
      icon : swassist_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    defauts:
      icon : defauts_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
  Utilitaires:
    traduitjdm: 
      pages:
        doc: index.html
        changeLog: release_notes.html
