langs:
  fr_FR : Français
  en_US : English
sass:
  sass_dir: _sass

monNom : ktn

plugins:
  - jemoji

docs:
  Plugins:
    defauts:
      icon : defauts_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    devolo_cpl:
      legacy: true
      icon: devolo_cpl_icon.png
      pages:
        doc: index.html
        changelog: changelog.html
    EaseeCharger:
      legacy: true
      icon: EaseeCharger_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    emulStore:
      legacy: true
      icon: emulStore_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    #EVcharger:
    #  icon : EVcharger_icon.png
    #  pages:
    #    doc utilisateurs: index.html
    #    changeLog: changelog.html
    #    Ajout d'un modèle: ajoutModel.html
    #    Cmd des chargeurs: cmdCharger.html
    SmartMeterUSB:
      legacy: true
      icon  : SmartMeterUSB_icon.png
      pages :
        doc : index.html
        changeLog: changelog.html
    swassist:
      legacy: true
      icon : swassist_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    velux:
      legacy: true
      icon : velux_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    volvocars:
      icon : volvocars_icon.png
      pages:
        doc: index.html
        changelog: changelog.html

  Utilitaires:
    traduitjdm: 
      legacy: true
      pages:
        doc: index.html
        changeLog: release_notes.html
