plugins:
  - jemoji
sass:
  sass_dir: _sass

monNom : ktn

docs:
  Plugins:
    defauts:
      icon : defauts_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    EaseeCharger:
      icon: EaseeCharger_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    emulStore:
      icon: emulStore_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    devolo_cpl:
      icon: devolo_cpl_icon.png
      pages:
        doc: index.html
        changelog: changelog.html
    #EVcharger:
    #  icon : EVcharger_icon.png
    #  pages:
    #    doc utilisateurs: index.html
    #    changeLog: changelog.html
    #    Ajout d'un modèle: ajoutModel.html
    #    Cmd des chargeurs: cmdCharger.html
    swassist:
      icon : swassist_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
    velux:
      icon : velux_icon.png
      pages:
        doc: index.html
        changeLog: changelog.html
  Utilitaires:
    traduitjdm: 
      pages:
        doc: index.html
        changeLog: release_notes.html
