name: Translate documentation

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/*/fr_FR/**'
      - 'index/fr_FR/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: Mips2648/docs-translations@v3
        with:
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          target_languages: "en_US,pt_PT"
          documents_roots: "plugins"
          memory_path: ${{ github.workspace }}/.translation_memory
